## Code

name: Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - '2_0_vulns/translations/**'
  pull_request:
    branches:
      - main
    paths:
      - '2_0_vulns/translations/**'

jobs:
  convert-markdown-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Using Node.js version 20

      - name: Configure locale
        run: |
          sudo locale-gen en_US.UTF-8
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
          echo "LANGUAGE=en_US.UTF-8" >> $GITHUB_ENV

      - name: Install necessary fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-indic fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          pip3 install python-bidi pdfplumber

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf

      - name: Run markdown_to_pdf.sh for each language
        run: |
            # Get the list of changed directories under 2_0_vulns/translations
            changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '2_0_vulns/translations/*' | \
            awk -F'/' '{print $1"/"$2"/"$3}' | sort -u)

            for dir in $changed_dirs; do
            abs_dir="$(pwd)/$dir"
            ../../.github/scripts/pdf-generation/md-to-pdf-v2.sh "$abs_dir"
            done
        working-directory: ${{ github.workspace }}/.github/scripts/pdf-generation

      - name: Get current date and time
        id: date
        run: echo "date=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: Upload generated PDFs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-translations-zipfile-${{ env.date }}
          path: ${{ github.workspace }}/.github/scripts/pdf-generation/generated/*.pdf
